### ISSUE TITLE
HCudaCheck FAIL

### ISSUE THREAD

**Issue by vitalishe** [ZichaoLong/PDE-Net#1]
Some issues with the install/run. Here is what I am doing after downloading the repository and aTEAM-0.1, which I rename into aTEAM (as was suggested).

`conda create -n PDE-Net python=3.6`
`source activate PDE-Net`

`conda install jupyter`
`conda install scipy`
`conda install pyyaml`
`conda install pytorch torchvision -c pytorch`

When running the 

`python learn-variantcoelinear2d.py`

`HCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1532579805626/work/aten/src/THC/THCGeneral.cpp line=74 error=30 : unknown error
Traceback (most recent call last):`
` File "learn_variantcoelinear2d.py", line 36, in <module>
   namestobeupdate, callback, linpdelearner = linpdeconfig.setenv(options)`
` File "/home/vgyrya/ML/PDE-Net/linpdeconfig.py", line 211, in setenv
   linpdelearner.cuda(namestobeupdate['gpu'])`
` File "/home/vgyrya/.conda/envs/PDE-Net/lib/python3.6/site-packages/torch/nn/modules/module.py", line 258, in cuda
   return self._apply(lambda t: t.cuda(device))`
` File "/home/vgyrya/.conda/envs/PDE-Net/lib/python3.6/site-packages/torch/nn/modules/module.py", line 185, in _apply
   module._apply(fn)`
` File "/home/vgyrya/.conda/envs/PDE-Net/lib/python3.6/site-packages/torch/nn/modules/module.py", line 185, in _apply
   module._apply(fn)`
` File "/home/vgyrya/.conda/envs/PDE-Net/lib/python3.6/site-packages/torch/nn/modules/module.py", line 185, in _apply
   module._apply(fn)`
` File "/home/vgyrya/.conda/envs/PDE-Net/lib/python3.6/site-packages/torch/nn/modules/module.py", line 197, in _apply
   self._buffers[key] = fn(buf)`
` File "/home/vgyrya/.conda/envs/PDE-Net/lib/python3.6/site-packages/torch/nn/modules/module.py", line 258, in <lambda>
   return self._apply(lambda t: t.cuda(device))`
`RuntimeError: cuda runtime error (30) : unknown error at /opt/conda/conda-bld/pytorch_1532579805626/work/aten/src/THC/THCGeneral.c
pp:74`

**Comment by chenxingqiang** [comment]
pls use python3
