### ISSUE TITLE
win10可以用吗？

### ISSUE THREAD

**Issue by ctscsu** [ZichaoLong/PDE-Net#4]

**Comment by chenxingqiang** [comment]
可以的。

**Comment by ctscsu** [comment]
> 可以的。

win10跑出来bug好多啊

**Comment by Userneam** [comment]
I am also having a lot of issues with windows 10. I don't even know where to start.

What packages are required? For instance, tensorflow, jupyter notebook, scipy, torch, are there other that are needed that is not stated? 

Should this program be used on Jupyter notebook?

I had an issue with  the program not being able to use "TimeStepper"

I also don't know how my directory should look in order for this to run. Does everything need to be installed in my python 3.7 folder? Where should I put aTEAM?

**Comment by ZichaoLong** [comment]
> I am also having a lot of issues with windows 10. I don't even know where to start.
We do not test on windows, but since this project is purely python code, I think it will be OK to run in windows.
