### ISSUE TITLE
Timeout during printing the current expression

### ISSUE THREAD

**Issue by ankitesh97** [ZichaoLong/PDE-Net#8]
I am getting a timeout during the training of the burger's equation. This timeout is during the printing
of the coefficients. Also, some of the losses has become NaNs. Below is the snippet of the output

```
finally, finish this stage
iter:   345    time: 10.09
Func: 2.71e+03  |g|: 3.76e+02
stableloss: 1.29e+02   dataloss: 2.71e+03   sparseloss: 5.60e+02 momentloss: 7.27e+00
current expression:
Time out
block:  1
name:  test
device:  cuda:0
generate a random number to check random seed:  -0.7672237767185355
```

**Comment by ZichaoLong** [comment]
NaN losses imply failed to learn the expression of the equations. We calculate coefficient by symbolic tools(SymPy) which is a time-consuming process especially when the learned expression is complex.

**Comment by ankitesh97** [comment]
Thanks for the information
